use_frameworks!

target 'OMChartView_Example' do
  pod 'OMChartView', :path => '../'

  target 'OMChartView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
